config/routes.rb
Timeline::Application.routes.draw do
  resources :comments

  resources :workspaces do
    resources :tickets
    resources :members
  end

  resource :account

  devise_for :users

  root :to => 'dashboard#index'

end

app/models/workspace.rb
class Workspace < ActiveRecord::Base
  validates :name, presence: true

  has_many  :tickets, dependent: :destroy
  
  has_many  :members, dependent: :destroy 
  has_many  :users, through: :members
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @workspaces = self.current_user.workspaces.all
  end

  def show
    @workspace = self.current_user.workspaces.find(params[:id])
  end

  def new
    @workspace = self.current_user.workspaces.new
  end

  def edit
    @workspace = self.current_user.workspaces.find(params[:id])
  end

  def create
    @workspace = self.current_user.workspaces.new(params[:workspace])

    if @workspace.save
      @workspace.users << self.current_user
      redirect_to @workspace, notice: 'Workspace was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @workspace = Workspace.find(params[:id])

    if @workspace.update_attributes(params[:workspace])
      redirect_to @workspace, notice: 'Workspace was successfully updated.'
    else
      render action: "edit" 
    end
  end

  def destroy
    @workspace = Workspace.find(params[:id])
    @workspace.destroy

    redirect_to workspaces_url
  end
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/_form.html.haml
= semantic_form_for @workspace do |f|
  = f.inputs do
    = f.input :name
    = f.input :public
  
  = f.buttons do
    = f.commit_button

app/views/workspaces/edit.html.haml
%h1 Editing workspace

= render 'form'

= link_to 'Show', @workspace
\|
= link_to 'Back', workspaces_path

app/views/workspaces/index.html.haml
.row-fluid
  .span4
    %h3 Activity Feed
        
  .span8
    .page-header
      %h3 
        MacBury
        %small workspaces

    %table.zebra-striped.bordered-table
      %tr
        %th Name

      - @workspaces.each do |workspace|
        %tr
          %td= link_to workspace.name, workspace



%br

= link_to 'New Workspace', new_workspace_path, class: "btn btn-large btn-primary"

app/views/workspaces/new.html.haml
.page-header
  %h1
    .pull-right= link_to 'Back', workspaces_path, class: "btn danger"
    New workspace

= render 'form'

app/views/workspaces/show.html.haml
- content_for :head do
  = faye_meta(workspace_path(@workspace), "current_workspace")
- content_for :header do
  .btn-toolbar
    .btn-group.pull-right
      %a.btn.btn-primary#add_ticket{ href: "#" }
        %i.icon-plus-sign.icon-white
        Add Ticket
    .btn-group{ data: { toggle: "buttons-checkbox" } }
      = link_to t("views.done"), "#", class: "btn btn-info", id: "done_space_button"
      = link_to t("views.current"), "#", class: "btn btn-info", id: "current_space_button"
      = link_to t("views.backlog"), "#", class: "btn btn-info", id: "pending_space_button"
    .btn-group
      %a.btn.dropdown-toggle{ data: { toggle: "dropdown" }, href: "#" }
        %i.icon-cog
        Workspace
        %span.caret
      %ul.dropdown-menu
        %li= link_to "Enter distraction Free Mode", "#"
        %li.divider
        %li= link_to "Settings", "#"
        %li= link_to "Members", workspace_members_path(@workspace)
    .btn-group
      %a.btn.dropdown-toggle{ data: { toggle: "dropdown" }, href: "#" }
        %i.icon-road
        Tickets
        %span.caret
      %ul.dropdown-menu
        %li= link_to "Refresh", workspace_path(@workspace), id: "refresh"
        %li= link_to "Settings", "#"
        %li.divider
        %li= link_to "Download as CSV", workspace_tickets_path(@workspace, format: :csv)

- content_for :footer do
  :javascript
    $(document).ready(function(){
      window.timeline = new Timeline.Routers.TicketsRouter({ 
        users: #{render partial: "users/members.json.builder", locals: { users: @workspace.users } },
        url: #{workspace_tickets_path( workspace_id: @workspace.id).inspect.html_safe} 
      });
      Backbone.history.start();
    });

.spaces
  %table#spaces
    %tr
      %td Loading... Please Wait...