config/routes.rb
Timeline::Application.routes.draw do
  resources :comments

  resources :workspaces do
    resources :tickets
    resources :members
  end

  resource :account

  devise_for :users

  root :to => 'dashboard#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t("application.name")
    = csrf_meta_tags
    = javascript_include_tag File.join(Faye::Url, "faye.js")
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    :javascript
      $(document).ready(function(){
        window.user_id = #{user_signed_in? ? self.current_user.id : -1}
        I18n.defaultLocale = #{I18n.default_locale.to_s.inspect};
        I18n.locale = #{I18n.locale.to_s.inspect};
      });
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon" }/
    = yield :head
  %body{ :id => "controller_#{controller.controller_name}_#{controller.action_name}" }
    .navbar.navbar-fixed-top.top_bar
      .navbar-inner
        .container-fluid
          = link_to root_url, class: "brand" do
            = t("application.name")
          - if user_signed_in?
            %ul.nav
              %li.divider-vertical
              %li.dropdown
                = link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do
                  - if @workspace && !@workspace.new_record?
                    = @workspace.name
                  - else
                    Select Workspace
                  %b.caret
                %ul.dropdown-menu
                  - self.current_user.workspaces.each do |workspace|
                    %li= link_to workspace.name, workspace
                  %li.divider
                  %li= link_to "Show All", workspaces_path
              %li.divider-vertical
            %ul.nav.pull-right
              %li.dropdown
                = link_to "#", class: "dropdown-toggle", id: "notifications", data: { toggle: "dropdown" } do
                  %i.icon-white.icon-inbox
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "test", "#"
              %li
                = link_to account_path do
                  %i.icon-white.icon-cog
              %li.divider-vertical
              %li
                = link_to "#" do
                  %i.icon-white.icon-off
          - else
            %p.pull-right Test :P
      .clear
    .header= yield :header
    .clear
    = render partial: "shared/flash_messages"
    .clear
    .container-fluid
      = yield
      .clear
    .cursor= image_tag "cursor_load.gif"
    = yield :footer